import { createOwnedTextNode, isRendererOwned } from '../../renderer-owned-nodes';
import { VNode } from '../../vnode/types';
import { FiberNode } from './types';
import { createFiberTree } from './fiber-tree';
import { FiberScheduler, FiberReconcileFunction } from './fiber-scheduler';
import { FiberPriority } from './types';
import { DOMOperations } from '../../dom-operations';
import { ComponentManager } from '../../component-manager';
import { handlePortalVNode } from '../utils/portal-handler';
import { handleVNodeTextProperty, handlePrimitiveTextChild } from '../utils/text-node-handlers';
import { getVNodeId } from '../utils/vnode-utils';
import {
  transferVNodeIdFromPrev,
  generateVNodeIdIfNeeded,
  findOrCreateHost,
  updateChildFiberParents
} from './fiber-reconciler-helpers';
import { getHostSibling } from './get-host-sibling';
import { isAutoGeneratedSid } from '../../vnode/utils/sid-source';
import { logger, LogCategory } from '../../utils/logger';
import { EffectTag } from './types';
import { VNodeTag, DOMAttribute } from '../../vnode/types';

/**
 * Dependencies required for Fiber reconcile
 */
export interface FiberReconcileDependencies {
  dom: DOMOperations;
  components: ComponentManager;
  currentVisitedPortalIds: Set<string> | null;
  portalHostsById: Map<string, { target: HTMLElement, host: HTMLElement }>;
  // Additional information for root-level processing
  rootModel?: any; // Model reference for model.text processing
  rootSid?: string; // sid of rootVNode
  context?: any; // Reconciliation context (for unmountComponent)
  prevRootFiber?: FiberNode | null; // React-style: previous Fiber tree (used as alternate)
  /**
   * Called with the scheduler a render is about to run on.
   *
   * The caller keeps it so that the *next* render can cancel this one. Work
   * yields and resumes from an idle callback, so two renders overlap on a busy
   * machine, and the one that started first must not paint over the one that
   * started second.
   */
  onSchedulerStart?: (scheduler: { cancel: () => void }) => void;
}

/**
 * Get decorator identity (data-decorator-sid) from VNode (attrs or top-level decoratorSid).
 */
function getDecoratorSid(node: VNode | undefined): string | undefined {
  if (!node || typeof node !== 'object') return undefined;
  const fromAttrs = (node as VNode & { attrs?: Record<string, unknown> }).attrs?.[DOMAttribute.DECORATOR_SID];
  if (fromAttrs !== undefined && fromAttrs !== null) return String(fromAttrs);
  return (node as VNode & { decoratorSid?: string }).decoratorSid;
}

/**
 * Check Props changes via shallow comparison
 */
function arePropsEqual(prev: any, next: any): boolean {
  if (prev === next) return true;
  if (!prev || !next) return false;
  
  const prevKeys = Object.keys(prev);
  const nextKeys = Object.keys(next);
  
  if (prevKeys.length !== nextKeys.length) return false;
  
  for (const key of nextKeys) {
    if (prev[key] !== next[key]) return false;
  }
  
  return true;
}

/**
 * Fiber-based reconcile
 * 
 * Convert VNode tree to Fiber tree and process each Fiber node individually
 * 
 * @param container - Root container element
 * @param vnode - VNode tree to reconcile
 * @param prevVNode - Previous VNode (for diffing)
 * @param context - Reconciliation context
 * @param deps - Dependencies required for Fiber reconcile
 * @param onComplete - Callback to be called when Fiber work completes (optional)
 */
export function reconcileWithFiber(
  container: HTMLElement,
  vnode: VNode,
  prevVNode: VNode | undefined,
  context: any,
  deps: FiberReconcileDependencies,
  onComplete?: (rootFiber: FiberNode) => void
): void {
  // React-style: set previous rootFiber as alternate
  const prevRootFiber = deps.prevRootFiber || null;
  
  // 1. Create Fiber tree (pass previous rootFiber as alternate)
  const rootFiber = createFiberTree(container, vnode, prevVNode, context, null, 0, prevRootFiber);
  
  // 2. Define Fiber render function (Render Phase)
  // Only calculate changes for each Fiber node (no DOM manipulation)
  const fiberRender: FiberReconcileFunction = (fiber: FiberNode) => {
    renderFiberNode(fiber, deps, context);
    delete (fiber as any).__isReturningToParent;
  };
  
  // 3. Custom FiberScheduler that sets __isReturningToParent flag when returning to parent
  class CustomFiberScheduler extends FiberScheduler {
    protected performUnitOfWork(fiber: FiberNode): FiberNode | null {
      // 1. Render current Fiber (Render Phase)
      this.reconcileFiber(fiber);
      
      // 2. If child exists, return child (next work)
      if (fiber.child) {
        return fiber.child;
      }
      
      // 3. Return sibling if exists
      if (fiber.sibling) {
        return fiber.sibling;
      }
      
      // 4. Go back to parent and find sibling
      // IMPORTANT: When going back to parent, all children of parent have been processed,
      // so must perform parent's post-processing (remove primitive text, stale decorator)
      let nextFiber = fiber.return;
      while (nextFiber) {
        // When going back to parent, all children of parent have been processed,
        // so call fiberReconcile again on parent to perform post-processing
        // Set __isReturningToParent flag to perform post-processing
        (nextFiber as any).__isReturningToParent = true;
        this.reconcileFiber(nextFiber);
        
        if (nextFiber.sibling) {
          return nextFiber.sibling;
        }
        nextFiber = nextFiber.return;
      }
      
      return null; // Complete
    }
  }
  
  // 4. Start work with Fiber Scheduler (async yield)
  const scheduler = new CustomFiberScheduler(fiberRender, () => {
    // Execute Commit Phase after Render Phase completes
    commitFiberTree(rootFiber, deps, context);
    if (onComplete) {
      onComplete(rootFiber);
    }
  });

  /**
   * Only the newest render paints.
   *
   * Work yields and resumes from an idle callback, so two renders overlap
   * whenever the machine is busy: the second builds its tree from the first's
   * *previous* one — the first has not committed yet — draws, and then the
   * first wakes up and draws its own, older tree on top. The page went back a
   * keystroke while the document stayed right, and nothing asked again because
   * nothing had changed since.
   */
  deps.onSchedulerStart?.(scheduler);

  scheduler.scheduleWork(rootFiber, FiberPriority.Normal);
}

/**
 * 단일 Fiber 노드를 render (Render Phase)
 * DOM 조작 없이 변경사항만 계산하고 effectTag 설정
 * 
 * @param fiber - 처리할 Fiber 노드
 * @param deps - 필요한 의존성
 * @param context - Reconciliation context
 */
export function renderFiberNode(
  fiber: FiberNode,
  deps: FiberReconcileDependencies,
  context: any
): void {
  const { dom, components, currentVisitedPortalIds, portalHostsById } = deps;
  
  // Primitive text is not converted to Fiber, so only process VNode here
  const vnode = fiber.vnode;
  // React style: get prevVNode from alternate (fiber.prevVNode is deprecated)
  const prevVNode = fiber.alternate?.vnode || fiber.prevVNode;
  const parent = fiber.parent;
  
  // IMPORTANT: Transfer ID from prevVNode to nextVNode (when ID is missing)
  transferVNodeIdFromPrev(vnode, prevVNode);
  
  // IMPORTANT: When auto-generated sid is needed, use stype and index to generate consistent ID
  generateVNodeIdIfNeeded(vnode, fiber, deps.components);
  
  // 1. Handle Portal
  if (handlePortalVNode(
    vnode,
    dom,
    (host, prev, next, ctx) => {
      // Portal internal reconcile is handled separately
      // Reconcile directly without following Fiber structure
      const portalFiber = createFiberTree(host, next, prev, ctx);
      const portalScheduler = new FiberScheduler((f: FiberNode) => {
        renderFiberNode(f, deps, ctx);
      }, () => {
        // Portal also executes commit phase
        commitFiberTree(portalFiber, deps, ctx);
      });
      portalScheduler.scheduleWork(portalFiber, FiberPriority.Normal);
    },
    currentVisitedPortalIds,
    portalHostsById
  )) {
    // Portal is handled, so exit here
    return;
  }
  
  // 2. If nextVNode is absent, call unmountComponent if prevVNode exists
  if (!vnode || typeof vnode !== 'object') {
    // Call unmountComponent if prevVNode exists and has stype
    if (prevVNode && prevVNode.stype && prevVNode.sid) {
      const prevHost = prevVNode.meta?.domElement;
      if (prevHost && prevHost instanceof Element) {
        try {
          components.unmountComponent(prevVNode, context);
        } catch (err) {
          logger.error(LogCategory.FIBER, 'Error unmounting component in renderFiberNode', err);
        }
      }
    }
    return;
  }
  
  // If no tag and no text but children exist, add children directly to parent
  // (e.g., when wrapped in root VNode)
  if (!vnode.tag && vnode.children && vnode.children.length > 0) {
    // Fiber scheduler automatically handles children
    // Here, only set DOM element reference (using parent)
      if (!vnode.meta) {
        vnode.meta = {};
      }
    vnode.meta.domElement = parent;
    fiber.domElement = parent;
    
    // 4-1. Update direct child Fibers' parent to current parent
    updateChildFiberParents(fiber, parent);
    
    // Fiber scheduler automatically performs children processing
    return;
    }
  
  // If no tag, no text, and no children, nothing to process
  if (!vnode.tag && !vnode.text) {
    return;
  }
  
  if (vnode.text !== undefined && (!vnode.children || vnode.children.length === 0)) {
    logger.debug(LogCategory.FIBER, 'text vnode detected', {
      sid: vnode.sid,
      tag: vnode.tag,
      text: vnode.text,
      parentTag: parent?.nodeType === 1 ? (parent as HTMLElement).tagName : parent?.nodeName
    });
  }
  
  // 3. Type comparison (reconcile rule: cannot reuse if types differ)
  const isTextVNode = (node: VNode) => node.tag === VNodeTag.TEXT || (!node.tag && node.text !== undefined);
  const isHostVNode = (node: VNode) => node.tag && node.tag !== VNodeTag.TEXT;
  
  const prevType = prevVNode 
    ? (isTextVNode(prevVNode) ? 'text' : isHostVNode(prevVNode) ? 'host' : 'unknown')
    : null;
  const nextType = isTextVNode(vnode) ? 'text' : isHostVNode(vnode) ? 'host' : 'unknown';
  // The tag IS the type (React compares `type` directly): two host nodes with
  // different tags are different elements and must not share a DOM node.
  // Comparing only text-vs-host let a <br> be "updated" into a <span>, which
  // rendered nothing at all because <br> is void and cannot take children.
  const tagChanged =
    prevType === 'host' && nextType === 'host' && prevVNode!.tag !== vnode.tag;
  /**
   * And for a **component**, the type is its `stype` rather than the tag it happens to draw.
   *
   * Two different node types can draw the same element — a placement and a frame are both a `div`
   * here — so the tag said "the same thing" and this took the UPDATE path, keeping the DOM element.
   * `ComponentManager.updateComponent` then saw the `stype` change, and *it* is right that a
   * different component is a different thing: it unmounted the old one, which **took that very
   * element out of the document**, and mounted the new one with nothing left to attach to.
   *
   * The result was a node that changed type disappearing off the page while the document held it
   * perfectly — found in a site builder, detaching a component. Two answers to "is this the same
   * thing", one of them made after the other had already reused the DOM.
   */
  const componentChanged =
    !!prevVNode?.stype && !!vnode.stype && prevVNode.stype !== vnode.stype;
  const typeChanged = (prevType !== null && prevType !== nextType) || tagChanged || componentChanged;

  // Host nodes with different decorator identity must not reuse DOM (create new element)
  const prevDecoratorSid = getDecoratorSid(prevVNode);
  const nextDecoratorSid = getDecoratorSid(vnode);
  const decoratorIdentityChanged =
    isHostVNode(vnode) &&
    (prevDecoratorSid !== undefined || nextDecoratorSid !== undefined) &&
    prevDecoratorSid !== nextDecoratorSid;
  
  // 4. Determine effectTag (calculation only, no DOM manipulation)
  // PLACEMENT if no prevVNode, PLACEMENT if type changed (remove existing DOM then create new), UPDATE otherwise
  if (!prevVNode || typeChanged || decoratorIdentityChanged) {
    fiber.effectTag = EffectTag.PLACEMENT;
  } else {
    fiber.effectTag = EffectTag.UPDATE;
  }
  
  // 5. Create or find DOM element (React style: create DOM in Render Phase)
  // In Render Phase, create DOM but do not insert
  // IMPORTANT: If type changed or decorator identity changed, do not reuse existing DOM, create new
  let domElement: HTMLElement | Text | null = null;
  
  const cannotReuse = typeChanged || decoratorIdentityChanged;
  // Find existing DOM element (from prevVNode, reuse only if type and decorator identity are same)
  if (prevVNode?.meta?.domElement && !cannotReuse) {
    domElement = prevVNode.meta.domElement as HTMLElement | Text;
  } else {
    // Create new DOM element (insertion performed in commit phase)
    if (vnode.tag === VNodeTag.TEXT || (!vnode.tag && vnode.text !== undefined)) {
      // Create text node
      const doc = parent.ownerDocument || document;
      const expectedText = String(vnode.text);
      domElement = createOwnedTextNode(expectedText, doc);
    } else if (vnode.tag) {
      const { dom } = deps;

      /**
       * A node that **owns its DOM** is asked for its element rather than given one.
       *
       * `mount(props, container): HTMLElement` says so in its own signature, and the return value
       * used to be recorded on the instance and used for nothing: `createComponentVNode` hard-codes
       * `tag: 'div'`, so a component drawing a `pre` got a `div` with a `pre` inside it — one
       * element per such node that nobody asked for, in the editor and in every published page.
       *
       * Which is the claim not being kept rather than a detail. *The component owns its DOM* has to
       * mean the element too, or the renderer still decides what the node is and only lets the
       * component fill it in.
       *
       * Mounted **here**, in the render phase, for the same reason React creates before it inserts:
       * the element has to exist before the commit can place it, and placing a `div` and then
       * swapping it for the component's would be two writes and a flash where there is one write and
       * none. The commit knows not to mount again — `fiber.meta.mounted` says so.
       */
      const owned = ownsItsDom(fiber, deps)
        ? mountOwnElement(vnode, parent, deps)
        : undefined;

      if (owned) {
        domElement = owned;
        if (!fiber.meta) fiber.meta = {};
        fiber.meta.mounted = true;
      } else {
        // Create host element (do not insert)
        domElement = dom.createSimpleElement(String(vnode.tag));
      }

      // Set VNode identifier attributes
      if (vnode.sid && !isAutoGeneratedSid(vnode)) {
        dom.setAttribute(domElement, DOMAttribute.BC_SID, String(vnode.sid));
      }
      
      // Set attrs (decorator information, etc.)
      if (vnode.attrs) {
        for (const [key, value] of Object.entries(vnode.attrs)) {
          if (value !== undefined && value !== null) {
            dom.setAttribute(domElement, key, String(value));
          }
        }
      }
      // VNode top-level decorator identity: copy to DOM as data-decorator-* attributes
      if ((vnode as VNode & { decoratorSid?: string }).decoratorSid != null) {
        dom.setAttribute(domElement, DOMAttribute.DECORATOR_SID, String((vnode as VNode & { decoratorSid?: string }).decoratorSid));
      }
      if ((vnode as VNode & { decoratorStype?: string }).decoratorStype != null) {
        dom.setAttribute(domElement, DOMAttribute.DECORATOR_STYPE, String((vnode as VNode & { decoratorStype?: string }).decoratorStype));
      }
    }
  }
  
  // Store DOM element reference
  if (!vnode.meta) {
    vnode.meta = {};
  }
  vnode.meta.domElement = domElement;
  fiber.domElement = domElement;
  
  // 7. Primitive text children processing is performed after child Fiber processing
  // (handled in performUnitOfWork when there are no children)
  
  // 8. Child Fiber nodes are automatically handled by FiberScheduler
  // performUnitOfWork returns fiber.child to set as next work

  // React approach: maintain previous state using Fiber tree's alternate instead of prevVNodeTree
  // No separate storage needed
}

/**
 * Commit Fiber tree (Commit Phase)
 * Traverse all Fiber nodes and perform DOM operations according to effectTag
 * 
 * @param rootFiber - Root Fiber node
 * @param deps - Required dependencies
 * @param context - Reconciliation context
 */
export function commitFiberTree(
  rootFiber: FiberNode,
  deps: FiberReconcileDependencies,
  context: any
): void {
  // Traverse Fiber tree and perform commit
  let currentFiber: FiberNode | null = rootFiber;
  
  while (currentFiber) {
    // Commit current Fiber
    commitFiberNode(currentFiber, deps, context);
    
    // If child exists, move to child
    if (currentFiber.child) {
      currentFiber = currentFiber.child;
      continue;
    }
    
    // If no child (all children committed), perform post-processing
    // Process primitive text and remove stale children
    if (currentFiber.primitiveTextChildren && currentFiber.primitiveTextChildren.length > 0) {
      processPrimitiveTextChildren(currentFiber, deps);
    }
    removeStaleChildren(currentFiber, deps);
    
    // If sibling exists, move to sibling
    if (currentFiber.sibling) {
      currentFiber = currentFiber.sibling;
      continue;
    }
    
    // Return to parent to find sibling
    // Also perform parent's post-processing when returning (all children committed)
    let parentFiber: FiberNode | null = currentFiber.return;
    while (parentFiber && !parentFiber.sibling) {
      // Perform parent's post-processing
      if (parentFiber.primitiveTextChildren && parentFiber.primitiveTextChildren.length > 0) {
        processPrimitiveTextChildren(parentFiber, deps);
      }
      removeStaleChildren(parentFiber, deps);
      
      parentFiber = parentFiber.return;
    }
    if (parentFiber) {
      // Perform parent's post-processing
      if (parentFiber.primitiveTextChildren && parentFiber.primitiveTextChildren.length > 0) {
        processPrimitiveTextChildren(parentFiber, deps);
      }
      removeStaleChildren(parentFiber, deps);
      
      currentFiber = parentFiber.sibling;
    } else {
      currentFiber = null;
    }
  }
}

/**
 * 단일 Fiber 노드를 commit (Commit Phase)
 * effectTag에 따라 DOM 조작 수행
 * 
 * @param fiber - 처리할 Fiber 노드
 * @param deps - 필요한 의존성
 * @param context - Reconciliation context
 */
export function commitFiberNode(
  fiber: FiberNode,
  deps: FiberReconcileDependencies,
  context: any
): void {
  const { dom, components } = deps;
  const vnode = fiber.vnode;
  // React approach: get prevVNode from alternate (fiber.prevVNode is deprecated)
  const prevVNode = fiber.alternate?.vnode || fiber.prevVNode;
  const parent = fiber.parent;
  
  // If no effectTag, do not process
  if (!fiber.effectTag) {
    return;
  }
  
  // Portal is handled separately (already processed in render phase)
  // TODO: Portal should also be moved to commit phase
  
  // If no vnode, handle DELETION
  if (!vnode || typeof vnode !== 'object') {
    if (fiber.effectTag === EffectTag.DELETION && prevVNode) {
      const prevHost = prevVNode.meta?.domElement;
      if (prevHost && prevHost instanceof Element) {
        try {
          components.unmountComponent(prevVNode, context);
        } catch (err) {
          logger.error(LogCategory.FIBER, 'Error unmounting component in commitFiberNode', err);
        }
        if (prevHost.parentNode) {
          prevHost.parentNode.removeChild(prevHost);
        }
      }
    }
    return;
  }
  
  // If no tag and no text but has children, add children directly to parent
  if (!vnode.tag && vnode.children && vnode.children.length > 0) {
    if (!vnode.meta) {
      vnode.meta = {};
    }
    vnode.meta.domElement = parent;
    fiber.domElement = parent;
    updateChildFiberParents(fiber, parent);
    return;
  }
  
  // If no tag, no text, and no children, nothing to process
  if (!vnode.tag && !vnode.text) {
    return;
  }
  
  // React approach: In Commit Phase, only perform DOM insertion
  // DOM elements are already created in Render Phase, so only insertion is performed here
  const domElement = fiber.domElement;
  
  if (!domElement) {
    // Error if domElement is missing (should be created in Render Phase)
    logger.error(LogCategory.FIBER, 'domElement is not set. Render Phase should create it.');
    return;
  }
  
  // Type comparison (reconcile rule: if type changes, remove existing DOM and insert new)
  const isTextVNode = (node: VNode) => node.tag === VNodeTag.TEXT || (!node.tag && node.text !== undefined);
  const isHostVNode = (node: VNode) => node.tag && node.tag !== VNodeTag.TEXT;
  
  const prevType = prevVNode 
    ? (isTextVNode(prevVNode) ? 'text' : isHostVNode(prevVNode) ? 'host' : 'unknown')
    : null;
  const nextType = isTextVNode(vnode) ? 'text' : isHostVNode(vnode) ? 'host' : 'unknown';
  // The tag IS the type (React compares `type` directly): two host nodes with
  // different tags are different elements and must not share a DOM node.
  // Comparing only text-vs-host let a <br> be "updated" into a <span>, which
  // rendered nothing at all because <br> is void and cannot take children.
  const tagChanged =
    prevType === 'host' && nextType === 'host' && prevVNode!.tag !== vnode.tag;
  // A different `stype` is a different component, whatever element it draws — see the render phase.
  const componentChanged =
    !!prevVNode?.stype && !!vnode.stype && prevVNode.stype !== vnode.stype;
  const typeChanged = (prevType !== null && prevType !== nextType) || tagChanged || componentChanged;
  
  // If type changed: remove existing DOM
  if (typeChanged && prevVNode?.meta?.domElement) {
    const prevDomElement = prevVNode.meta.domElement;
    if (prevDomElement.parentNode) {
      prevDomElement.parentNode.removeChild(prevDomElement);
    }
    // Component unmount (only for HTMLElement)
    if (prevDomElement instanceof Element && prevVNode.stype && prevVNode.sid) {
      try {
        components.unmountComponent(prevVNode, context);
      } catch (err) {
        console.error('[Fiber.commitFiberNode] Error unmounting component:', err);
      }
    }
  }
  
  // React's commitPlacement: only perform DOM insertion
  if (fiber.effectTag === EffectTag.PLACEMENT) {
    let actualParent: HTMLElement | null = null;
    let parentCandidate = fiber.parentFiber;
    while (parentCandidate && !actualParent) {
      if (parentCandidate.domElement instanceof Element) {
        actualParent = parentCandidate.domElement;
        break;
      }
      parentCandidate = parentCandidate.parentFiber;
    }
    if (!actualParent && parent instanceof Element) {
      actualParent = parent;
    }
    
    // React's getHostSibling: find next sibling's DOM node
    let before = getHostSibling(fiber);
    
    if (!actualParent) {
      logger.error(LogCategory.FIBER, 'actualParent is not available for placement', {
        fiberVNode: {
          sid: vnode.sid,
          tag: vnode.tag,
          text: vnode.text
        },
        parentFiberVNode: fiber.parentFiber?.vnode,
        parentNodeType: parent?.nodeType,
        parentNodeValue: (parent as any)?.nodeValue
      });
      return;
    }
    
    // Check if before node is a child of actualParent
    // In React's commit phase, the next sibling may not have been committed yet,
    // so the before node may not be a child of actualParent
    // In this case, set before to null to handle same as appendChild
    if (before && before.parentNode !== actualParent) {
      before = null;
    }
    
    // DOM insertion (same as React's commitPlacement)
    if (!(actualParent instanceof Element)) {
      logger.error(LogCategory.FIBER, 'actualParent is not HTMLElement', {
        fiberVNode: {
          sid: vnode.sid,
          tag: vnode.tag,
          text: vnode.text
        },
        parentFiberVNode: {
          sid: fiber.parentFiber?.vnode?.sid,
          tag: fiber.parentFiber?.vnode?.tag,
          text: fiber.parentFiber?.vnode?.text
        },
        parentNodeType: actualParent != null ? (actualParent as Node).nodeType : undefined,
        parentNodeValue: (actualParent as any)?.nodeValue
      });
    }


    if (domElement.parentNode !== actualParent) {
      // If DOM element is not in parent, insert
      actualParent.insertBefore(domElement, before);
    } else if (domElement.nextSibling !== before && before !== domElement) {
      // If DOM element is in parent but at wrong position, move
      actualParent.insertBefore(domElement, before);
    }
  } else if (fiber.effectTag === EffectTag.UPDATE && domElement instanceof Element) {
    // Reorder when reused node is at wrong position (child order changed)
    let actualParent: HTMLElement | null = null;
    let parentCandidate = fiber.parentFiber;
    while (parentCandidate && !actualParent) {
      if (parentCandidate.domElement instanceof Element) {
        actualParent = parentCandidate.domElement;
        break;
      }
      parentCandidate = parentCandidate.parentFiber;
    }
    if (!actualParent && parent instanceof Element) {
      actualParent = parent;
    }
    if (actualParent && domElement.parentNode === actualParent) {
      const before = getHostSibling(fiber);
      const beforeInParent = before && before.parentNode === actualParent ? before : null;
      if (domElement.nextSibling !== beforeInParent && beforeInParent !== domElement) {
        actualParent.insertBefore(domElement, beforeInParent);
      }
    }
  }
  
  /**
   * The **order** of siblings, once each of them is in the DOM.
   *
   * ## Why the two branches above are not enough
   *
   * Both place a node *before the next one* (`getHostSibling`), and that is only correct if
   * everything after it is already where it belongs. The commit walks children left to right, so it
   * never is. Measured, at four lines of test: `[a, b, c]` becoming `[b, c, a]` drew `[c, b, a]`, and
   * a reversal came out as a rotation. Every product had it — a slide moved in the filmstrip, a block
   * moved up in a document, a card dragged along a row — and nothing looked at the drawn order, so
   * nothing caught it.
   *
   * ## What this does instead
   *
   * Each host child goes **after the one committed before it**, which is the one thing already known
   * to be in the right place. Left to right, that is enough to sort any permutation, and the first
   * child never has to move at all — everything else is arranged around it.
   *
   * Only when the two are genuinely **inverted**, never merely apart: a parent holds things no fiber
   * owns — a caret filler, a decorator's chrome — and a rule that closed every gap would drag them
   * along. So a node moves only when the sibling that should precede it is drawn after it.
   */
  if (domElement && domElement.parentNode) {
    let orderedIn: Element | null = null;
    let above = fiber.parentFiber;
    while (above && !orderedIn) {
      if (above.domElement instanceof Element) orderedIn = above.domElement;
      above = above.parentFiber;
    }
    if (!orderedIn && parent instanceof Element) orderedIn = parent;

    if (orderedIn && domElement.parentNode === orderedIn) {
      const placed: Map<Element, Node> = context.__placedSiblings ?? (context.__placedSiblings = new Map());
      const before = placed.get(orderedIn);
      if (
        before &&
        before !== domElement &&
        before.parentNode === orderedIn &&
        // `before` is drawn *after* me, so the two are the wrong way round.
        (domElement.compareDocumentPosition(before) & Node.DOCUMENT_POSITION_FOLLOWING) !== 0
      ) {
        orderedIn.insertBefore(domElement, before.nextSibling);
      }
      placed.set(orderedIn, domElement);
    }
  }

  if (fiber.effectTag === EffectTag.PLACEMENT) {
    // Component lifecycle: mount when component VNode has stype
    // IMPORTANT: do not call mountComponent for already mounted components
    if (domElement instanceof Element && vnode.stype) {
      const componentManager = components as any;
      let shouldMount = false;
      
      if (vnode.sid) {
        // Check if component is already mounted (check by sid)
          const existingInstance = componentManager.getComponentInstance(vnode.sid);
          // Mount needed if existingInstance is missing or mounted is false or element is different
          if (!existingInstance || !existingInstance.mounted || existingInstance.element !== domElement) {
            shouldMount = true;
          }
      } else {
        // If no sid: check with generateComponentId
        const componentId = componentManager.generateComponentId(vnode, fiber.index);
        if (componentId && typeof componentManager.getComponentInstance === 'function') {
          const existingInstance = componentManager.getComponentInstance(componentId);
          if (!existingInstance || !existingInstance.mounted || existingInstance.element !== domElement) {
            shouldMount = true;
          }
        } else {
          shouldMount = true;
        }
      }
      
      /*
       * Unless the render phase already did it. A node that owns its DOM is mounted there, because
       * its element *is* what the commit is about to place — see `mountOwnElement`.
       */
      if (shouldMount && !fiber.meta?.mounted) {
        try {
          components.mountComponent(vnode, domElement, context || ({} as any));
        } catch (err) {
          logger.error(LogCategory.FIBER, 'Error mounting component', err);
        }
      }
    }
  }
  
  // Store DOM element reference (already set in Render Phase, but ensure it)
  if (!vnode.meta) {
    vnode.meta = {};
  }
  vnode.meta.domElement = domElement;
  
  // Update text node (Text VNode)
  // Reconcile rule: compare prevVNode and nextVNode to update
  if (domElement instanceof Text) {
    const nextText = vnode.text !== undefined ? String(vnode.text) : '';
    const currentText = domElement.textContent || ''; // Current text in actual DOM
    
    // Update if type hasn't changed and text is different
    if (!typeChanged && currentText !== nextText) {
      logger.debug(LogCategory.FIBER, 'updating Text node', {
        vnodeSid: vnode.sid,
        before: currentText,
        after: nextText
      });
      // Update through DOMOperations (traceable in AutoTracer)
      dom.updateTextContent(domElement, currentText, nextText);
    }
    return;
  }
  
  // Update parent of direct child Fibers to current domElement (only if HTMLElement)
  if (domElement instanceof Element) {
    /**
     * Text the reused element is still holding that the new VNode has no room
     * for.
     *
     * An element kept across a render keeps its DOM children, and the ones the
     * reconciler does not account for have to be taken away. Text is the case
     * nothing else covers: a child *element* that has gone is removed as a stale
     * fiber, but a text node the new tree has no VNode for is invisible to that
     * pass, so it simply stays where it is.
     *
     * The test is what the new VNode says, not what the old one said. It used to
     * ask whether the *previous* VNode was text-only, which is the same question
     * only when the pairing is one level deep — and the pairing that matters here
     * is two:
     *
     *     before   <span class="mark-bold"><span>bb</span></span>
     *     after    <span class="mark-bold"><span class="mark-italic"><span>bb</span></span></span>
     *
     * Nesting a second mark inserts a wrapper, so the inner span pairs with the
     * *outer* one and inherits its element — which is holding "bb". Its previous
     * VNode had a child, not text, so the old test said no, and the element kept
     * the text while the new inner span added it again: "a bb c" drew as
     * "a bbbb c".
     *
     * Only where the wrappers share a tag, which is why it went unseen. Marks
     * defined as `<strong>` and `<em>` cannot pair with a plain `<span>`, so a
     * fresh element gets built and the stale text goes with the old one. Both
     * products define their marks as spans with classes, so both doubled text on
     * the second mark — and the observer then read that doubled DOM back as
     * typing and wrote it into the model, which is the nineteen-fold corruption
     * in `docs/BACKLOG.md`. This is its root; the observer only amplified it.
     */
    const isTextChild = (child: unknown): boolean => {
      if (typeof child === 'string' || typeof child === 'number') return true;
      if (!child || typeof child !== 'object') return false;
      const node = child as VNode;
      return node.tag === VNodeTag.TEXT || (!node.tag && node.text !== undefined);
    };
    const nextChildren = Array.isArray(vnode.children) ? vnode.children : [];
    const nextDrawsOwnText = vnode.text !== undefined || nextChildren.some(isTextChild);
    if (nextChildren.length > 0 && !nextDrawsOwnText) {
      /**
       * Ours to remove; anyone else's to leave.
       *
       * A text node this renderer made and no longer has a VNode for is stale by
       * definition — it is the leftover being cleaned up here. A text node it did
       * not make is the browser's, and between a keystroke and the sync that node
       * *is* what the reader just typed; an IME composes straight into the
       * element. Removing those loses input, which
       * `test/core/foreign-node-cleanup.test.ts` holds the line on.
       */
      for (const node of Array.from(domElement.childNodes)) {
        if (node.nodeType === Node.TEXT_NODE && isRendererOwned(node)) {
          domElement.removeChild(node);
        }
      }
    }
    
    updateChildFiberParents(fiber, domElement);
  }
  
  // Update attributes and styles (only if HTMLElement)
  // Optimization: only call update if changed
  if (domElement instanceof Element) {
    // Effective attrs: vnode.attrs + VNode top-level decorator identity (data-decorator-sid, data-decorator-stype)
    const effectiveAttrs: Record<string, string> = { ...(vnode.attrs || {}) };
    const vnodeWithDecorator = vnode as VNode & { decoratorSid?: string; decoratorStype?: string };
    if (vnodeWithDecorator.decoratorSid != null) {
      effectiveAttrs[DOMAttribute.DECORATOR_SID] = String(vnodeWithDecorator.decoratorSid);
    }
    if (vnodeWithDecorator.decoratorStype != null) {
      effectiveAttrs[DOMAttribute.DECORATOR_STYPE] = String(vnodeWithDecorator.decoratorStype);
    }
    const prevEffectiveAttrs: Record<string, string> = { ...(prevVNode?.attrs || {}) };
    const prevWithDecorator = prevVNode as (VNode & { decoratorSid?: string; decoratorStype?: string }) | undefined;
    if (prevWithDecorator?.decoratorSid != null) {
      prevEffectiveAttrs[DOMAttribute.DECORATOR_SID] = String(prevWithDecorator.decoratorSid);
    }
    if (prevWithDecorator?.decoratorStype != null) {
      prevEffectiveAttrs[DOMAttribute.DECORATOR_STYPE] = String(prevWithDecorator.decoratorStype);
    }
    /**
     * A **replaced** element is diffed against nothing.
     *
     * The comparison below asks what changed since the previous vnode and writes only that, which is
     * right for an element being kept — a write that changes nothing still produces a mutation
     * record, and the input path reads those to work out what a reader typed.
     *
     * It is wrong for an element that has just been *made*. When the type changed, the old DOM node
     * was removed a few lines above and a new one created, so it has none of the old one's
     * attributes — and every property the two templates declare **the same way** was skipped as
     * unchanged. Measured in a site builder: one board drew a page and was then pointed at a
     * component's definition; a `surface` declares `display: flex` and so does a `frame`, and the
     * new element came out `display: block` with every *other* declaration in place.
     */
    const replaced = typeChanged;
    const wasAttrs = replaced ? {} : prevEffectiveAttrs;
    const wasStyle = replaced ? undefined : prevVNode?.style;

    if (Object.keys(effectiveAttrs).length > 0 || Object.keys(wasAttrs).length > 0) {
      if (replaced || !arePropsEqual(wasAttrs, effectiveAttrs)) {
        dom.updateAttributes(domElement, wasAttrs, effectiveAttrs);
      }
    }
    if (vnode.style) {
      const prevStyle = wasStyle;
      if (replaced || !arePropsEqual(prevStyle, vnode.style)) {
        dom.updateStyles(domElement, prevStyle, vnode.style as any);
      }
    }
    
    // Component lifecycle: update when component VNode has stype
    // IMPORTANT: skip updateComponent if __isReconciling flag is set (prevent infinite loop)
    if (vnode.stype && fiber.effectTag === EffectTag.UPDATE) {
      const isReconciling = !!(context as any)?.__isReconciling;
      
      if (!isReconciling) {
        try {
          components.updateComponent(
            prevVNode || ({} as VNode),
            vnode,
            domElement,
            context || ({} as any)
          );
        } catch (error) {
          logger.error(
            LogCategory.FIBER,
            `Error updating component ${vnode.stype} (sid: ${vnode.sid})`,
            error
          );
        }
      }
    }
  }
  
  // Handle vnode.text (when VNodeBuilder collapsed text, only if HTMLElement)
  if (domElement instanceof Element) {
    if (vnode.text !== undefined && (!vnode.children || vnode.children.length === 0)) {
      logger.debug(LogCategory.FIBER, 'handling vnode.text', {
        vnodeSid: vnode.sid,
        text: vnode.text,
        parentTag: domElement.tagName
      });
      handleVNodeTextProperty(domElement, vnode, prevVNode);
      return;
    }
    
    // Handle root-level model.text (if rootModel is provided)
    if (deps.rootModel && deps.rootSid && vnode.sid === deps.rootSid) {
      const model = deps.rootModel;
      if ((model as any)?.text !== undefined && (model as any)?.text !== null) {
        if (!vnode.children || vnode.children.length === 0) {
          const doc = domElement.ownerDocument || document;
          while (domElement.firstChild) domElement.removeChild(domElement.firstChild);
          domElement.appendChild(createOwnedTextNode(String((model as any).text), doc));
          return;
        }
      }
    }
  }
}

/**
 * Stale children 제거
 * 자식 Fiber가 모두 처리된 후에 호출됨
 * 현재 children에 없는 자식 요소를 DOM에서 제거
 * 
 * IMPORTANT: VNode만 순수하게 처리 (decorator 구분 없음)
 */
/**
 * Whether this fiber's node draws itself — `external({ managesDOM: true })`.
 *
 * Asked of the registry rather than remembered on the vnode, because the vnode is rebuilt on every
 * render and the registration is not: one is a fact about the drawing and the other about the node
 * type, and the second is the one that decides who owns the element.
 */
function ownsItsDom(fiber: FiberNode, deps: FiberReconcileDependencies): boolean {
  const stype = fiber.vnode?.stype;
  if (!stype) return false;

  // The same two places `mountComponent` looks, in the same order.
  const context = deps.context as
    | {
        getComponent?: (one: string) => unknown;
        registry?: { getComponent?: (one: string) => unknown };
      }
    | undefined;
  const component = (context?.getComponent?.(stype) ??
    context?.registry?.getComponent?.(stype)) as { managesDOM?: boolean } | undefined;

  return component?.managesDOM === true;
}

/**
 * Ask a self-drawing component for its element, and take what it gives.
 *
 * The container it is handed is the **parent** the element will be placed in, not a wrapper made for
 * it — a component that appends to the container rather than returning is drawing into the parent,
 * which is what the old shape encouraged and what the wrapper existed to contain. Returning is the
 * contract; appending as well is harmless and its element is still the one adopted.
 */
function mountOwnElement(
  vnode: VNode,
  parent: HTMLElement,
  deps: FiberReconcileDependencies
): HTMLElement | undefined {
  try {
    const made = deps.components.mountComponent(vnode, parent, (deps.context || {}) as never);
    return made instanceof Element ? (made as HTMLElement) : undefined;
  } catch (err) {
    logger.error(LogCategory.FIBER, 'Error mounting a component that manages its own DOM', err);
    return undefined;
  }
}

export function removeStaleChildren(
  fiber: FiberNode,
  deps: FiberReconcileDependencies
): void {
  const host = fiber.domElement;
  if (!host || !(host instanceof Element)) {
    return;
  }

  /**
   * Unless the node **owns its own DOM**, in which case none of it is this function's to judge.
   *
   * A component registered with `external({ managesDOM: true })` draws itself — a code editor, a
   * chart, an embed, anything the renderer cannot express as elements. What it puts inside its
   * element has no fiber, because no fiber built it, so every sweep here found the whole of it
   * unaccounted for and removed it. Measured: `mount` ran, appended, and the element was empty by
   * the time anyone looked.
   *
   * The claim is the component's and the renderer's job is to keep out of it.
   */
  if (ownsItsDom(fiber, deps)) return;
  
  // IMPORTANT: prevVNode matching already completed in createFiberTree based on sid/key/index/tag
  // domElement of each Fiber child is set in renderFiberNode
  // DOM insertion is completed in commitFiberNode
  // Therefore, simply track used DOM elements by traversing Fiber children
  // However, must collect recursively to handle nested structures
  
  // Track used DOM elements (based on Fiber children, recursively)
  const usedDomElements = new Set<HTMLElement | Text>();
  const collectDomElements = (f: FiberNode | null) => {
    while (f) {
      const el = f.domElement;
      if (el instanceof Element || el instanceof Text) {
        usedDomElements.add(el);
      }
      // Also collect children recursively (handle nested structures)
      if (f.child) {
        collectDomElements(f.child);
        }
      f = f.sibling;
    }
  };
  collectDomElements(fiber.child);
  
  // Find all child nodes in DOM
  const childNodes = Array.from(host.childNodes);
  const components = deps.components;
  const context = deps.context || {};
  
  // Remove unused DOM elements only (do not remove Text nodes)
  // Text nodes are managed by handleVNodeTextProperty and processPrimitiveTextChildren,
  // and are not in usedDomElements (no Fiber for primitive/vnode.text).
  for (const childNode of childNodes) {
    if (usedDomElements.has(childNode as HTMLElement | Text)) {
      continue; // Keep used elements
    }
    if (childNode.nodeType === Node.TEXT_NODE) {
      // Text nodes this renderer produced (vnode.text, primitive children) have
      // no fiber of their own, so they are absent from usedDomElements and must
      // be kept.
      if (isRendererOwned(childNode)) continue;

      // An unowned text node here was put there by the browser — an IME composing
      // straight into the DOM, or contenteditable inventing structure.
      //
      // It is NOT swept, deliberately. Text input reaches the model by observing
      // the DOM and diffing it (see the MutationObserver path), so between the
      // keystroke and the sync the browser's text node IS the user's input. A
      // re-render landing in that window would delete what was just typed —
      // measured in Chrome: typing and IME composition into a fresh block both
      // lost their text outright.
      //
      // Making this safe needs a signal that the model has absorbed the DOM (or
      // that the caret is elsewhere); ownership tracking above is the half of it
      // that exists today.
      continue;
    }

    // Remove unused DOM elements (HTMLElement only)
    if (childNode instanceof Element) {
      // Component unmount (only if sid exists)
      const sid = childNode.getAttribute(DOMAttribute.BC_SID);
      if (sid) {
        // Find in prevVNode and unmount
        // React approach: get prevVNode from alternate
        const prevVNode = fiber.alternate?.vnode || fiber.prevVNode;
        if (prevVNode?.children) {
          const prevChildVNode = prevVNode.children.find(
          (c): c is VNode => {
            if (typeof c !== 'object' || c === null) return false;
            const prevId = getVNodeId(c);
              return prevId === sid;
          }
        );
        if (prevChildVNode && prevChildVNode.stype && prevChildVNode.sid) {
          try {
            components.unmountComponent(prevChildVNode, context);
          } catch (err) {
            logger.error(LogCategory.FIBER, 'Error unmounting component in removeStaleChildren', err);
          }
        }
        }
      }

      try {
        host.removeChild(childNode);
      } catch {
        // May have already been removed
      }
    }
  }
}

/**
 * Process primitive text children
 * Called after all child Fibers are processed
 */
export function processPrimitiveTextChildren(
  fiber: FiberNode,
  deps: FiberReconcileDependencies
): void {
  if (!fiber.primitiveTextChildren || fiber.primitiveTextChildren.length === 0) {
    return;
  }
  
  const host = fiber.domElement;
  if (!host || !(host instanceof Element)) {
    return;
  }
  
  const vnode = fiber.vnode;
  // React approach: get prevVNode from alternate
  const prevVNode = fiber.alternate?.vnode || fiber.prevVNode;
  const prevChildVNodes: (VNode | string | number)[] = prevVNode?.children || [];
  
  logger.debug(LogCategory.FIBER, 'processPrimitiveTextChildren start', {
    hostTag: host instanceof Element ? host.tagName : VNodeTag.TEXT,
    vnodeSid: vnode.sid,
    primitiveCount: fiber.primitiveTextChildren.length,
    prevChildrenCount: prevChildVNodes.length
  });
  
  // Track already used text nodes (prevent duplicates)
  const usedTextNodes = new Set<Text>();
  
  // Process each primitive text
  // Use handlePrimitiveTextChild to create/update text nodes at correct positions
  // IMPORTANT: primitive text children must be mixed with VNode children,
  // so use index as-is to insert at correct position
  // DOM childNodes correspond 1:1 with VNode children, so can use index as-is
  // However, processPrimitiveTextChildren is called after all child Fibers are processed,
  // so must consider VNode children already added to DOM
  // Calculate DOM node count of all children (VNode + primitive text) before index
  // VNode children are already added to DOM, so check in DOM childNodes
  // Primitive text is not yet added to DOM, so only count VNode children
  for (const { text, index } of fiber.primitiveTextChildren) {
    logger.debug(LogCategory.FIBER, 'processPrimitiveTextChildren', {
      hostTag: (host as HTMLElement).tagName,
      text,
      index,
      vnodeSid: vnode.sid,
      prevText: prevChildVNodes[index]
    });
    // Calculate DOM node count of VNode children before index
    // VNode children are already added to DOM, so check in DOM childNodes
    let domNodeCount = 0;
    if (vnode.children) {
      for (let j = 0; j < index; j++) {
        const prevChild = vnode.children[j];
        if (typeof prevChild === 'object' && prevChild !== null) {
          // VNode is already added to DOM, so count
          const childVNode = prevChild as VNode;
          const childDomElement = childVNode.meta?.domElement;
          if (childDomElement && (childDomElement instanceof Element || childDomElement instanceof Text)) {
            domNodeCount++;
        }
        }
        // Primitive text is not yet added to DOM, so don't count
        // (processed in same loop)
      }
    }
    
    // Process text node using handlePrimitiveTextChild
    // childIndex uses domNodeCount (number of nodes already added to DOM before index)
    // Pass usedTextNodes to exclude already used text nodes
    const textNode = handlePrimitiveTextChild(host, text, domNodeCount, usedTextNodes);
    
    // Add used text node to tracking
    usedTextNodes.add(textNode);
  }
}
