import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { sharedSidebarItems } from './navigation';
const sidebars: SidebarsConfig = { packages: [...sharedSidebarItems('packages'), { type: 'autogenerated', dirName: '.' }] };
export default sidebars;
