import { expect, test } from '@playwright/test';

test('Site row Note insertion survives crossing another block and its short editor boundary and persists after reload', async ({ page }, info) => {
  await page.goto('/');
  await page.locator('[data-admin-tab="data"]').click();
  await page.locator('[data-admin-open="글"]').click();
  await page.locator('[data-row-open="0"]').click();
  const field = page.locator('[data-row-form] [data-field="본문"]');
  const body = field.locator('[data-note-body]');
  const summary = page.locator('[data-row-form] [data-field="요약"] [data-note-body]');
  const unchangedSummary = await summary.innerText();
  const targetText = '쌓임은 브라우저가 이미 아는 문법이고, 좌표는 우리가 폭마다 다시 말해야 하는 것입니다.';
  const target = body.locator('.on-doc > p').filter({ hasText: targetText });
  const before = body.locator('.on-doc > p').filter({ hasText: '자유 배치가 페이지에 필요하다고 믿었고' });
  const originalParagraphs = await body.locator('.on-doc > p').allTextContents();
  await target.click({ position: { x: 40, y: 10 } });
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+ArrowLeft' : 'Home');
  for (let index = 0; index < '쌓임'.length; index++) await page.keyboard.press('Shift+ArrowRight');
  await expect.poll(() => page.evaluate(() => document.getSelection()?.toString())).toBe('쌓임');
  await target.hover();
  await field.getByRole('button', { name: '블록 추가', exact: true }).click();
  const menu = field.locator('[data-note-insert]');
  const quote = menu.locator('[data-note-control="insertQuote"]');
  await expect(quote).toBeVisible();
  await before.hover();
  await expect(quote).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.getSelection()?.toString())).toBe('쌓임');
  const quoteBox = await quote.boundingBox();
  const bodyBox = await field.locator('.on-body-hold').boundingBox();
  if (!quoteBox || !bodyBox) throw new Error('Site insertion menu geometry is missing');
  expect(quoteBox.y + quoteBox.height / 2).toBeGreaterThan(bodyBox.y + bodyBox.height);
  await info.attach('site-insertion-geometry', { body: JSON.stringify({ quoteBox, bodyBox }), contentType: 'application/json' });
  await page.mouse.move(quoteBox.x + quoteBox.width / 2, quoteBox.y + quoteBox.height / 2, { steps: 20 });
  await expect(quote).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.getSelection()?.toString())).toBe('쌓임');
  await page.mouse.click(quoteBox.x + quoteBox.width / 2, quoteBox.y + quoteBox.height / 2);
  await expect(menu).toHaveCount(0);
  const inserted = body.locator('.on-doc > blockquote');
  await expect(inserted).toHaveCount(1);
  await expect(inserted.locator('xpath=preceding-sibling::*[1]')).toHaveText(targetText);
  await expect(body.locator('.on-doc > p')).toHaveText(originalParagraphs);
  await expect(summary).toHaveText(unchangedSummary);

  // Input through the actual inserted block, then flush by closing the row.
  await inserted.locator('p').click();
  await page.keyboard.press('End');
  await page.keyboard.insertText(' SITE-HOST-INSERT-279');
  await expect(inserted).toContainText('SITE-HOST-INSERT-279');
  await page.keyboard.press('Escape');
  await expect(page.locator('[data-row-form]')).toHaveCount(0);
  await expect(page.locator('[data-site-save-status]')).toHaveText('저장됨');
  await page.reload();
  await page.locator('[data-admin-tab="data"]').click();
  await page.locator('[data-admin-open="글"]').click();
  await page.locator('[data-row-open="0"]').click();
  await expect(inserted).toContainText('SITE-HOST-INSERT-279');
  await expect(body.locator('.on-doc > p')).toHaveText(originalParagraphs);
  await expect(summary).toHaveText(unchangedSummary);
  await expect(inserted.locator('xpath=preceding-sibling::*[1]')).toHaveText(targetText);
});

test('Site row insertion dismisses and reopens without closing the host and its table size menu stays usable', async ({ page }) => {
  await page.goto('/');
  await page.locator('[data-admin-tab="data"]').click();
  await page.locator('[data-admin-open="글"]').click();
  await page.locator('[data-row-open="0"]').click();
  const row = page.locator('[data-row-form]');
  const field = row.locator('[data-field="본문"]');
  const body = field.locator('[data-note-body]');
  const targetText = '쌓임은 브라우저가 이미 아는 문법이고, 좌표는 우리가 폭마다 다시 말해야 하는 것입니다.';
  const target = body.locator('.on-doc > p').filter({ hasText: '쌓임은' });
  const originalParagraphs = await body.locator('.on-doc > p').allTextContents();
  const menu = field.locator('[data-note-insert]');
  const trigger = field.getByRole('button', { name: '블록 추가', exact: true });
  await target.hover();
  await trigger.click();
  await expect(menu).toBeVisible();
  await row.locator('[data-field="제목"] input').click();
  await expect(menu).toHaveCount(0);
  await expect(row).toBeVisible();
  await target.hover();
  await trigger.click();
  await expect(menu).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(menu).toHaveCount(0);
  await expect(row).toBeVisible();
  // A click in the body dismisses the menu and still places a native editing caret.
  await target.hover();
  await trigger.click();
  await expect(menu).toBeVisible();
  await target.click({ position: { x: 40, y: 10 } });
  await expect(menu).toHaveCount(0);
  await page.keyboard.press('End');
  await page.keyboard.insertText(' BODY-CLICK-279');
  await expect(target).toContainText('BODY-CLICK-279');
  await page.keyboard.press('ControlOrMeta+z');
  await expect(target).toHaveText(targetText);
  await expect(body.locator('.on-doc > p')).toHaveText(originalParagraphs);
  await target.hover();
  await trigger.click();
  await expect(menu).toBeVisible();
  // Escape from the native editing target must close only its menu.
  await page.keyboard.press('Escape');
  await expect(menu).toHaveCount(0);
  await expect(row).toBeVisible();
  await target.hover();
  await trigger.click();
  await expect(menu).toBeVisible();
  await body.locator('.on-doc > h2').hover();
  const tableAction = menu.locator('[data-note-control="insertTableBlock"]');
  await expect(tableAction).toBeVisible();
  const actionBox = await tableAction.boundingBox();
  if (!actionBox) throw new Error('Site table menu action geometry is missing');
  await page.mouse.move(actionBox.x + actionBox.width / 2, actionBox.y + actionBox.height / 2, { steps: 20 });
  await expect(tableAction).toBeVisible();
  await page.mouse.click(actionBox.x + actionBox.width / 2, actionBox.y + actionBox.height / 2);
  const size = menu.getByRole('gridcell', { name: '3행 2열', exact: true });
  await expect(size).toBeVisible();
  const sizeBox = await size.boundingBox();
  if (!sizeBox) throw new Error('Site table size menu geometry is missing');
  await page.mouse.move(sizeBox.x + sizeBox.width / 2, sizeBox.y + sizeBox.height / 2, { steps: 20 });
  await expect(size).toBeVisible();
  await page.mouse.click(sizeBox.x + sizeBox.width / 2, sizeBox.y + sizeBox.height / 2);
  await expect(menu).toHaveCount(0);
  const table = body.locator('.on-doc > table');
  await expect(table).toHaveCount(1);
  await expect(table.locator('tr')).toHaveCount(3);
  for (const cells of await table.locator('tr').all()) await expect(cells.locator('th, td')).toHaveCount(2);
  await expect(table.locator('xpath=preceding-sibling::*[1]')).toHaveText(targetText);
  await expect(body.locator('.on-doc > p')).toHaveText(originalParagraphs);
  await expect(row).toBeVisible();
});
