/**
 * Component Identity Application Utilities
 * 
 * Pure functions for applying component identity (sid) to VNodes
 */

import { ModelData } from '@barocss/dsl';
import { VNode } from '../types';
import { isNonEmptyArray } from './type-checks';
import type { Decorator } from '../decorator';
import { markAutoGeneratedSid, markInheritedSid } from './sid-source';

/**
 * Apply component identity (sid) to VNode
 * 
 * @param vnode - VNode to apply identity to
 * @param data - Model data
 * @param options - Build options
 * @param currentBuildOptions - Current build options (for sid fallback)
 * @param componentManager - ComponentManager instance (for auto-generating sid when stype exists)
 */
export function applyComponentIdentity(
  vnode: VNode,
  data: ModelData,
  options?: {
    injectChild?: VNode;
    useDataAsSlot?: boolean;
    decorators?: Decorator[];
    sid?: string;
    sidInherited?: boolean;
  },
  currentBuildOptions?: { sid?: string },
  componentManager?: any
): void {
  // sid comes directly from model data (via options.sid or data.sid)
  // If sid is not provided but stype exists, auto-generate sid using ComponentManager
  const providedSid = (options && options.sid !== undefined) ? options.sid : 
                      (currentBuildOptions && currentBuildOptions.sid !== undefined) ? currentBuildOptions.sid :
                      (data as any)?.sid;
  
  if (providedSid) {
    // The element still gets the attribute — the input path relies on it to find
    // the owning node — but reconciliation must not read it as identity.
    if (options?.sidInherited) {
      markInheritedSid(vnode, String(providedSid));
    } else {
      vnode.sid = String(providedSid);
    }
  } else if (vnode.stype && !vnode.sid && componentManager) {
    // Auto-generate sid when stype exists but sid is missing
    if (typeof componentManager.generateComponentId === 'function') {
      const generatedSid = componentManager.generateComponentId(vnode);
      if (generatedSid) {
        markAutoGeneratedSid(vnode, generatedSid);
      }
    }
  }
}

