import { VNode } from '../types';

/**
 * Mark a VNode's sid as auto-generated.
 * Stores the sid and records metadata so later stages can decide
 * whether the identifier should be exposed to the DOM.
 */
export function markAutoGeneratedSid(vnode: VNode, sid: string): void {
  vnode.sid = sid;
  if (!vnode.meta) {
    vnode.meta = {};
  }
  vnode.meta.sidAutogenerated = true;
}

/**
 * Determine whether a VNode's sid was auto-generated (not provided by model).
 */
export function isAutoGeneratedSid(vnode?: VNode | null): boolean {
  return !!vnode?.meta?.sidAutogenerated;
}


/**
 * Mark a VNode as carrying its *owner's* sid rather than its own.
 *
 * A node's id is propagated to every element of that node's template, so that a
 * DOM mutation anywhere inside it can be traced back to the node it belongs to.
 * That makes the sid an answer to "who owns this element", which is not the same
 * question as "which element is this" — and among siblings only the second one
 * can be used as identity. A template that draws three boxes gives all three the
 * same sid, and reconciliation cannot tell them apart.
 */
export function markInheritedSid(vnode: VNode, sid: string): void {
  vnode.sid = sid;
  if (!vnode.meta) {
    vnode.meta = {};
  }
  vnode.meta.sidInherited = true;
}

/** Whether a VNode's sid belongs to the node that owns it, not to the element. */
export function isInheritedSid(vnode?: VNode | null): boolean {
  return !!vnode?.meta?.sidInherited;
}
