import { VNode } from '../types';

/**
 * Mark a VNode's sid as auto-generated.
 * Stores the sid and records metadata so later stages can decide
 * whether the identifier should be exposed to the DOM.
 */
export function markAutoGeneratedSid(vnode: VNode, sid: string): void {
  vnode.sid = sid;
  if (!vnode.meta) {
    vnode.meta = {};
  }
  vnode.meta.sidAutogenerated = true;
}

/**
 * Determine whether a VNode's sid was auto-generated (not provided by model).
 */
export function isAutoGeneratedSid(vnode?: VNode | null): boolean {
  return !!vnode?.meta?.sidAutogenerated;
}

