export {
  type TextRun,
  type ContainerRuns,
  buildTextRunIndex,
  getTextRunsByElement,
  getTextRunsById,
  invalidateRunsByElement,
  invalidateRunsById,
  binarySearchRun,
  skipsInIndex,
  stripFiller,
  FILLER_CHAR,
  FILLER_ATTR,
  stripChromeElements,
  CHROME_ATTR,
} from './text-run-index';
