import { test, expect, type Page } from '@playwright/test';
async function expandMath(page: Page) {
  await page.getByLabel('노트 제목').focus();
  await page.getByLabel('본문 수식 도구', { exact: true }).getByRole('button', { name: '크게 편집', exact: true }).click();
}
test('body math inserts from slash, previews, rejects invalid source, edits and restores after reload', async ({ page }, info) => {
  await page.goto('/'); await expect(page.getByLabel('노트 제목')).toBeVisible();
  await page.getByRole('button', { name: '새 노트', exact: true }).click();
  const body = page.locator('[data-note-editor]').first();
  await body.locator('.on-doc p').first().click(); await page.keyboard.type('/');
  await page.locator('[data-slash-item="insertMathBlock"]').click();
  await body.getByRole('button', { name: '블록 수식 편집', exact: true }).click(); await expandMath(page);
  await page.getByRole('dialog', { name: '수학 수식' }).getByRole('tab', { name: 'LaTeX 원문', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '수학 수식' });
  await dialog.getByLabel('LaTeX 수식').fill('\\frac{a}{b} + x^2');
  await expect(dialog.locator('.katex')).toHaveCount(1);
  await expect(dialog.getByLabel('수식 크기', { exact: true })).toHaveCount(0);
  await expect(dialog.getByLabel('수식 미리보기')).toHaveCSS('font-size', '18px');
  await page.screenshot({ path: info.outputPath('math-editor.png') });
  await dialog.getByRole('button', { name: '수식 적용', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(body.locator('[data-latex-display="block"] .katex')).toHaveCount(1);
  await body.getByRole('button', { name: '블록 수식 편집', exact: true }).click();
  await page.getByLabel('노트 제목').focus();
  await page.getByLabel('수식 크기 바로 변경').selectOption('40');
  await expect(page.locator('.oe-math-inplace')).toHaveCSS('font-size', '40px');
  await page.getByLabel('수식 정렬', { exact: true }).selectOption('left');
  await page.getByLabel('수식 크기 바로 변경').selectOption('32');
  await page.getByLabel('본문 수식 도구', { exact: true }).getByRole('button', { name: '완료', exact: true }).click();
  await expect(body.locator('[data-latex-display="block"]')).toHaveCSS('text-align', 'left');
  await body.getByRole('button', { name: '블록 수식 편집', exact: true }).click(); await expandMath(page);
  await dialog.getByRole('tab', { name: 'LaTeX 원문', exact: true }).click();
  await dialog.getByLabel('LaTeX 수식').fill('\\frac{');
  await expect(dialog.getByRole('button', { name: '수식 적용', exact: true })).toBeDisabled();
  await dialog.getByRole('button', { name: '취소', exact: true }).click();
  await body.locator('.on-doc > p').last().click(); await page.keyboard.type('/');
  await page.locator('[data-slash-item="insertMathInline"]').click();
  await body.getByRole('button', { name: '인라인 수식 편집', exact: true }).click(); await expandMath(page);
  await page.getByRole('dialog', { name: '수학 수식' }).getByRole('tab', { name: 'LaTeX 원문', exact: true }).click();
  await dialog.getByLabel('LaTeX 수식').fill('E=mc^2');
  await dialog.getByRole('button', { name: '수식 적용', exact: true }).click();
  await expect(body.locator('[data-latex-display="inline"] .katex')).toHaveCount(1);
  await expect(body.locator('.on-doc')).not.toContainText('/');
  await expect(page.locator('[data-save-status]')).toHaveText('저장됨'); await page.reload();
  await expect(body.locator('[data-latex-node] .katex')).toHaveCount(2);
  await expect(body.getByRole('button', { name: '블록 수식 편집', exact: true })).toHaveCSS('font-size', '32px');
  await body.getByRole('button', { name: '블록 수식 편집', exact: true }).click(); await expandMath(page);
  await dialog.getByRole('tab', { name: 'LaTeX 원문', exact: true }).click();
  await expect(dialog.getByLabel('수식 크기', { exact: true })).toHaveCount(0);
  await expect(dialog.getByLabel('LaTeX 수식')).toHaveValue('\\frac{a}{b} + x^2');
});
