import { test, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const output = `${process.cwd()}/../../.dev/artifacts/design-system`;

test('adaptive panels preserve fields, show one compact panel and restore the docked layout', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 960 });
  await page.goto('/design-system/index.html#workspace');
  const sample = page.locator('#workspace');
  const root = sample.locator('.office-adaptive-workspace');
  const controls = sample.getByRole('group', { name: '작업 패널' });
  const left = root.locator('[data-workspace-panel=navigation]');
  const right = root.locator('[data-workspace-panel=inspector]');
  await expect(left).toBeHidden(); await expect(right).toBeHidden();
  await controls.getByRole('button', { name: '속성', exact: true }).click();
  await expect(right).toBeVisible(); await expect(left).toBeHidden();
  const input = right.getByRole('textbox', { name: '패널 예시 문서 이름' });
  await input.fill('검토한 출시 계획'); await input.press('Enter');
  // The field owns its first Escape. Tab transfers ownership to the workspace controls.
  await controls.getByRole('button', { name: '속성', exact: true }).focus(); await page.keyboard.press('Escape');
  await expect(right).toBeHidden();
  await expect(controls.getByRole('button', { name: '속성', exact: true })).toBeFocused();
  await controls.getByRole('button', { name: '탐색', exact: true }).click();
  await expect(left).toBeVisible();
  await controls.getByRole('button', { name: '속성', exact: true }).click();
  await expect(left).toBeHidden(); await expect(input).toHaveValue('검토한 출시 계획');
  await root.locator('[data-workspace-main]').click({ position: { x: 10, y: 250 } });
  await expect(right).toBeHidden();
  await sample.getByRole('combobox', { name: '작업 공간 예시 너비' }).click();
  await page.getByRole('option', { name: '1080px · 나란히 보기', exact: true }).click();
  await expect(left).toBeVisible(); await expect(right).toBeVisible(); await expect(controls).toHaveCount(0);
  await expect(input).toHaveValue('검토한 출시 계획');
  await page.setViewportSize({ width: 390, height: 800 });
  await expect(left).toBeHidden(); await expect(right).toBeHidden();
  await controls.getByRole('button', { name: '속성', exact: true }).click();
  await expect(right).toBeInViewport();
  expect(await right.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await mkdir(output, { recursive: true });
  await root.screenshot({ animations: 'disabled', path: `${output}/workspace-compact.png` });
});

test('Site retains usable canvas width and panel tabs through narrow and wide viewports', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.goto('/');
  await page.getByRole('button', { name: 'S Site 새 자료 만들기', exact: true }).click();
  await page.getByRole('textbox', { name: '새 자료 이름' }).fill('반응형 작업 공간');
  await page.getByRole('button', { name: '만들기', exact: true }).click();
  await expect(page.locator('[data-admin-open]')).toHaveCount(1);
  await page.locator('[data-admin-open=home]').click();
  const root = page.locator('.st-body');
  const controls = root.getByRole('group', { name: '작업 패널' });
  const left = root.locator('[data-workspace-panel=navigation]');
  const right = root.locator('[data-workspace-panel=inspector]');
  await expect(left).toBeVisible(); await expect(right).toBeVisible();
  await page.setViewportSize({ width: 560, height: 800 });
  await expect(left).toBeHidden(); await expect(right).toBeHidden();
  expect((await page.locator('.st-main').boundingBox())!.width).toBeGreaterThanOrEqual(550);
  await controls.getByRole('button', { name: '탐색', exact: true }).click();
  await left.getByRole('tab', { name: '페이지', exact: true }).click();
  await controls.getByRole('button', { name: '속성', exact: true }).click();
  await expect(left).toBeHidden(); await expect(right).toBeVisible();
  await controls.getByRole('button', { name: '탐색', exact: true }).click();
  await expect(left.getByRole('tab', { name: '페이지', exact: true })).toHaveAttribute('aria-selected', 'true');
  await controls.getByRole('button', { name: '탐색', exact: true }).focus(); await page.keyboard.press('Escape');
  await expect(left).toBeHidden();
  await mkdir(output, { recursive: true });
  await page.screenshot({ animations: 'disabled', path: `${output}/workspace-site-narrow.png` });
  await controls.getByRole('button', { name: '속성', exact: true }).click();
  await page.screenshot({ animations: 'disabled', path: `${output}/workspace-site-panel.png` });
  await page.setViewportSize({ width: 1440, height: 960 });
  await expect(left).toBeVisible(); await expect(right).toBeVisible(); await expect(controls).toHaveCount(0);
  await expect(left.getByRole('tab', { name: '페이지', exact: true })).toHaveAttribute('aria-selected', 'true');
  expect((await page.locator('.st-main').boundingBox())!.width).toBeGreaterThan(850);
});

test('Slides keeps object properties and navigation across compact panels and presentation', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.goto('/');
  await page.getByRole('button', { name: 'S Slides 새 자료 만들기', exact: true }).click();
  await page.getByRole('textbox', { name: '새 자료 이름' }).fill('반응형 슬라이드');
  await page.getByRole('button', { name: '만들기', exact: true }).click();
  const root = page.locator('.sl-body');
  const left = root.locator('[data-workspace-panel=navigation]');
  const right = root.locator('[data-workspace-panel=inspector]');
  const controls = root.getByRole('group', { name: '작업 패널' });
  await expect(left).toBeVisible(); await expect(right).toBeVisible();
  const frame = await page.locator('.sl-stage .sl-text-frame:visible').first().boundingBox();
  await page.mouse.click(frame!.x + frame!.width / 2, frame!.y + frame!.height / 2);
  const width = right.getByRole('spinbutton', { name: '너비', exact: true });
  await expect(width).toBeVisible();
  const originalWidth = await width.inputValue();
  await left.getByRole('tab', { name: '레이어', exact: true }).click();
  await page.setViewportSize({ width: 560, height: 800 });
  await expect(left).toBeHidden(); await expect(right).toBeHidden();
  expect((await page.locator('.sl-main').boundingBox())!.width).toBeGreaterThanOrEqual(550);
  await controls.getByRole('button', { name: '속성', exact: true }).click();
  await expect(width).toHaveValue(originalWidth);
  await width.fill('12.5'); await width.press('Enter');
  await controls.getByRole('button', { name: '탐색', exact: true }).click();
  await expect(right).toBeHidden();
  await expect(left.getByRole('tab', { name: '레이어', exact: true })).toHaveAttribute('aria-selected', 'true');
  await controls.getByRole('button', { name: '속성', exact: true }).click();
  await expect(width).toHaveValue('12.5');
  await mkdir(output, { recursive: true });
  await page.screenshot({ animations: 'disabled', path: `${output}/workspace-slides-panel.png` });
  await page.setViewportSize({ width: 390, height: 800 });
  await expect(right).toBeInViewport();
  expect(await right.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await controls.getByRole('button', { name: '속성', exact: true }).focus(); await page.keyboard.press('Escape');
  await expect(right).toBeHidden();
  await expect(controls.getByRole('button', { name: '속성', exact: true })).toBeFocused();
  await page.screenshot({ animations: 'disabled', path: `${output}/workspace-slides-narrow.png` });
  await page.setViewportSize({ width: 1440, height: 960 });
  await expect(left).toBeVisible(); await expect(right).toBeVisible(); await expect(controls).toHaveCount(0);
  await expect(width).toHaveValue('12.5');
  await expect(left.getByRole('tab', { name: '레이어', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.screenshot({ animations: 'disabled', path: `${output}/workspace-slides-wide.png` });
  await page.setViewportSize({ width: 560, height: 800 });
  await page.locator('[data-present]').click();
  await expect(page.locator('.sl-shell')).toHaveAttribute('data-presenting', 'true');
  await expect(left).toBeHidden(); await expect(right).toBeHidden();
  await expect(controls).toHaveCount(0);
  expect((await page.locator('.sl-main').boundingBox())!.width).toBeGreaterThanOrEqual(550);
  await page.keyboard.press('Escape');
  await expect(controls).toBeVisible(); await expect(left).toBeHidden(); await expect(right).toBeHidden();
});

test('Note compact navigation preserves search and writing while opening another page', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.goto('/');
  await page.getByRole('button', { name: 'N Note 새 자료 만들기', exact: true }).click();
  await page.getByRole('textbox', { name: '새 자료 이름' }).fill('패널 검증 첫 페이지');
  await page.getByRole('button', { name: '만들기', exact: true }).click();
  const root = page.locator('.nw-workspace');
  const left = root.locator('[data-workspace-panel=navigation]');
  const controls = root.getByRole('group', { name: '작업 패널' });
  const title = page.getByRole('textbox', { name: '노트 제목', exact: true });
  await expect(title).toHaveValue('패널 검증 첫 페이지');
  await expect(page.locator('.on-doc')).toBeVisible();
  await left.getByRole('button', { name: '새 노트', exact: true }).click();
  await expect(title).not.toHaveValue('패널 검증 첫 페이지');
  await title.fill('패널 검증 두 번째'); await title.press('Enter');
  const paragraph = page.locator('.on-doc > p').first();
  await paragraph.click(); await page.keyboard.type('Keep this writing.');
  await expect(paragraph).toContainText('Keep this writing.');
  await page.setViewportSize({ width: 390, height: 800 });
  await expect(left).toBeHidden();
  await expect(controls.getByRole('button')).toHaveCount(1);
  expect((await page.locator('.nw-main').boundingBox())!.width).toBeGreaterThanOrEqual(380);
  expect(await page.locator('.nw-main').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await controls.getByRole('button', { name: '탐색', exact: true }).click();
  const search = left.getByRole('searchbox', { name: '노트 검색' });
  await search.fill('패널 검증');
  await expect(left.locator('[data-page-id]')).toHaveCount(2);
  await controls.getByRole('button', { name: '탐색', exact: true }).focus(); await page.keyboard.press('Escape');
  await expect(left).toBeHidden();
  await expect(paragraph).toContainText('Keep this writing.');
  await controls.getByRole('button', { name: '탐색', exact: true }).click();
  await expect(search).toHaveValue('패널 검증');
  await mkdir(output, { recursive: true });
  await page.screenshot({ animations: 'disabled', path: `${output}/workspace-note-navigation.png` });
  await left.getByRole('button', { name: '패널 검증 첫 페이지', exact: true }).click();
  await expect(title).toHaveValue('패널 검증 첫 페이지');
  await expect(left).toBeHidden();
  await expect(page.locator('.nw-main')).toBeFocused();
  await controls.getByRole('button', { name: '탐색', exact: true }).click();
  await expect(search).toHaveValue('패널 검증');
  await left.getByRole('button', { name: '패널 검증 두 번째', exact: true }).click();
  await expect(left).toBeHidden();
  await expect(paragraph).toContainText('Keep this writing.');
  await paragraph.click(); await page.keyboard.press('End'); await page.keyboard.type(' More.');
  await expect(paragraph).toContainText('More.');
  await page.screenshot({ animations: 'disabled', path: `${output}/workspace-note-narrow.png` });
  await page.setViewportSize({ width: 1440, height: 960 });
  await expect(left).toBeVisible(); await expect(controls).toHaveCount(0);
  await expect(search).toHaveValue('패널 검증');
  await expect(left.locator('[aria-current=page]')).toHaveText('패널 검증 두 번째');
  await expect(paragraph).toContainText('More.');
});
