import { expect, test } from '@playwright/test';
test.beforeEach(async ({ page }) => { await page.goto('/design-system/index.html#commands'); });
test('search does not run disabled or composing input and remembers a command', async ({ page }) => {
  await page.getByRole('button', { name: '예시 명령 검색 열기', exact: true }).click();
  const query = page.getByRole('combobox', { name: '명령 검색어' });
  await expect(query).toBeFocused();
  await query.press('ArrowDown');
  await expect(page.getByRole('option', { name: /문서 설정/ })).toHaveAttribute('aria-selected', 'true');
  await query.press('ArrowUp');
  await expect(page.getByRole('option', { name: /굵게/ })).toHaveAttribute('aria-selected', 'true');
  await query.fill('셀 병합'); await query.press('Enter');
  await expect(page.getByRole('option')).toHaveAttribute('aria-disabled', 'true');
  await expect(page.getByRole('option')).toContainText('두 개 이상');
  await query.fill('굵게');
  await query.dispatchEvent('keydown', { key: 'Enter', isComposing: true });
  await expect(query).toBeVisible();
  await query.press('Enter');
  await expect(page.locator('#commands')).toContainText('실행: bold');
  await page.getByRole('button', { name: '예시 명령 검색 열기', exact: true }).click();
  await expect(page.getByRole('option').first()).toContainText('최근 사용');
  await query.fill('없는 명령'); await expect(page.getByRole('option')).toHaveCount(0);
  await expect(page.getByRole('dialog').getByRole('status')).toContainText('일치하는');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: '예시 명령 검색 열기', exact: true })).toBeFocused();
});
test('a follow-up dialog keeps focus after command search closes and fits mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 840 });
  await page.getByRole('button', { name: '예시 명령 검색 열기', exact: true }).click();
  await page.getByRole('combobox', { name: '명령 검색어' }).fill('문서 설정');
  await page.getByRole('combobox', { name: '명령 검색어' }).press('Enter');
  const next = page.getByRole('dialog', { name: '명령으로 연 문서 설정', exact: true });
  await expect(next).toBeVisible();
  await expect(page.getByRole('dialog', { name: '명령 검색', exact: true })).toHaveCount(0);
  await expect(next.getByRole('button', { name: '닫기', exact: true })).toBeFocused();
  await next.getByRole('textbox').fill('다음 창의 입력');
  await expect(next.getByRole('textbox')).toBeFocused();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '예시 명령 검색 열기', exact: true }).click();
  await page.screenshot({ path: '../../.dev/artifacts/design-system/command-search-mobile.png', animations: 'disabled' });
});
