import { expect, test, type Page, type Locator } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const output = `${process.cwd()}/../../.dev/artifacts/design-system`;
async function create(page: Page, product: string) {
  await page.goto('/');
  await page.getByRole('button', { name: `${product[0]} ${product} 새 자료 만들기`, exact: true }).click();
  await page.getByRole('textbox', { name: '새 자료 이름' }).fill('레이어 검증');
  await page.getByRole('button', { name: '만들기', exact: true }).click();
  await expect.poll(() => page.locator('[data-document-identity]').evaluate(el => el.querySelector('input')?.value || el.textContent?.trim())).toBe('레이어 검증');
}
const order = (rows: Locator) => rows.evaluateAll(rows => rows.map(row => row.getAttribute('data-layer')));
async function drag(page: Page, from: Locator, to: Locator) {
  const start = await from.boundingBox(), end = await to.boundingBox();
  expect(start).toBeTruthy(); expect(end).toBeTruthy();
  await page.mouse.move(start!.x + start!.width / 2, start!.y + start!.height / 2);
  await page.mouse.down();
  await page.mouse.move(end!.x + 50, end!.y + 2, { steps: 12 });
}
test('shared layer tools retain selection, reveal on focus and keep the row width stable', async ({ page }) => {
  await page.goto('/design-system/index.html#layers');
  const sample = page.locator('#layers');
  const title = sample.locator('[data-example-layer="title"]');
  const cover = sample.locator('[data-example-layer="cover"]');
  const width = await cover.locator('.office-layer-pick').evaluate(el => el.getBoundingClientRect().width);
  await cover.locator('.office-layer-pick').focus();
  await page.keyboard.press('Tab');
  const hide = cover.getByRole('button', { name: '표지 숨기기', exact: true });
  await expect(hide).toBeFocused();
  await expect(cover.locator('.office-layer-actions')).toHaveCSS('opacity', '1');
  await page.keyboard.press('Space');
  await expect(cover).toHaveAttribute('data-row-hidden', 'true');
  await expect(title).toHaveAttribute('data-row-selected', 'true');
  await expect(cover.locator('.office-layer-pick')).toHaveAttribute('aria-pressed', 'false');
  expect(await cover.locator('.office-layer-pick').evaluate(el => el.getBoundingClientRect().width)).toBe(width);
  await cover.getByRole('button', { name: '표지 접기', exact: true }).press('Enter');
  await expect(sample.locator('[data-example-layer]')).toHaveCount(1);
  await cover.getByRole('button', { name: '표지 펼치기', exact: true }).press('Space');
  await expect(title).toHaveAttribute('data-row-selected', 'true');
  await expect(sample.locator('button button')).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 740 });
  const panel = sample.locator('.ds-layer-panel');
  expect(await panel.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await mkdir(output, { recursive: true });
  await page.mouse.move(2, 2);
  await panel.screenshot({ path: `${output}/layers-light.png` });
  await page.getByRole('combobox', { name: '시스템 테마' }).click();
  await page.getByRole('option', { name: '어두운 테마', exact: true }).click();
  await panel.screenshot({ path: `${output}/layers-dark.png` });
});
test('Slides supports keyboard selection, independent row tools, reorder and cancel', async ({ page }) => {
  await create(page, 'Slides');
  await page.getByRole('tab', { name: '레이어', exact: true }).click();
  const rows = page.locator('.sl-layers-list [data-layer]');
  await expect(rows).toHaveCount(2);
  const ids = await order(rows);
  const first = page.locator(`[data-layer="${ids[0]}"]`), last = page.locator(`[data-layer="${ids[1]}"]`);
  await last.locator('.office-layer-pick').press('Space');
  await expect(last).toHaveAttribute('data-layer-selected', 'true');
  await first.hover();
  await first.locator('[data-layer-visible]').click();
  await expect(first).toHaveAttribute('data-layer-hidden', 'true');
  await expect(last).toHaveAttribute('data-layer-selected', 'true');
  await first.locator('[data-layer-visible]').click();
  await first.locator('button[data-layer-locked]').click();
  await expect(first).toHaveAttribute('data-layer-locked', 'true');
  await expect(last).toHaveAttribute('data-layer-selected', 'true');
  await first.locator('button[data-layer-locked]').click();
  await first.locator('button[data-layer-locked]').press('Delete');
  await expect(rows).toHaveCount(2);
  await expect(last).toHaveAttribute('data-layer-selected', 'true');
  await drag(page, last.locator('.office-layer-pick'), first);
  await page.keyboard.press('Escape'); await page.mouse.up();
  expect(await order(rows)).toEqual(ids);
  await drag(page, last.locator('.office-layer-pick'), first);
  await page.mouse.up();
  await expect.poll(() => order(rows)).toEqual([...ids].reverse());
  await page.keyboard.press('ControlOrMeta+z');
  await expect.poll(() => order(rows)).toEqual(ids);
  await mkdir(output, { recursive: true });
  await page.locator('.sl-sidebar').screenshot({ path: `${output}/layers-slides.png` });
});
test('Site has separate disclosure and tools, and cancels drops outside the list', async ({ page }) => {
  await create(page, 'Site');
  await page.locator('[data-admin-open]').first().click();
  await page.getByRole('tab', { name: '구성', exact: true }).click();
  const list = page.locator('[data-layers]'), rows = list.locator('[data-layer]');
  await expect(rows.first()).toBeVisible();
  await expect(list.locator('button button')).toHaveCount(0);
  const firstId = await rows.first().getAttribute('data-layer');
  const first = list.locator(`[data-layer="${firstId}"]`);
  await first.locator('.office-layer-pick').press('Enter');
  await expect(first).toHaveAttribute('data-selected', 'true');
  const disclosure = first.locator('.office-layer-disclosure');
  await disclosure.press('Enter');
  await expect(disclosure).toHaveAttribute('aria-expanded', 'true');
  await expect(first).toHaveAttribute('data-selected', 'true');
  await expect(rows).not.toHaveCount(1);
  const secondId = await rows.nth(1).getAttribute('data-layer');
  const second = list.locator(`[data-layer="${secondId}"]`);
  await second.hover();
  await second.locator('.office-layer-actions button').first().click();
  await expect(second).toHaveAttribute('data-hidden', 'true');
  await expect(first).toHaveAttribute('data-selected', 'true');
  await second.locator('.office-layer-actions button').last().press('Space');
  await expect(second).toHaveAttribute('data-locked', 'true');
  await expect(first).toHaveAttribute('data-selected', 'true');
  await second.locator('.office-layer-actions button').last().click();
  await first.locator('.office-layer-pick').click();
  await page.keyboard.press('ControlOrMeta+d');
  const blocks = list.locator('[data-stype="richText"]');
  await expect(blocks).toHaveCount(2);
  const movingId = await blocks.last().getAttribute('data-layer');
  const moving = list.locator(`[data-layer="${movingId}"]`);
  const before = await page.evaluate(() => JSON.stringify((window as any).editor.exportDocument()));
  await drag(page, moving.locator('.office-layer-pick'), first);
  await page.keyboard.press('Escape'); await page.mouse.up();
  expect(await page.evaluate(() => JSON.stringify((window as any).editor.exportDocument()))).toBe(before);
  await drag(page, moving.locator('.office-layer-pick'), first);
  await page.mouse.move(700, 250); await page.mouse.up();
  expect(await page.evaluate(() => JSON.stringify((window as any).editor.exportDocument()))).toBe(before);
  await drag(page, moving.locator('.office-layer-pick'), first);
  await page.mouse.up();
  await expect.poll(() => page.evaluate(() => JSON.stringify((window as any).editor.exportDocument()))).not.toBe(before);
  await page.keyboard.press('ControlOrMeta+z');
  await expect.poll(() => page.evaluate(() => JSON.stringify((window as any).editor.exportDocument()))).toBe(before);
  await mkdir(output, { recursive: true });
  await list.screenshot({ path: `${output}/layers-site.png` });
});
