export {
  bestContainer,
  closestDataNode,
  collapseBoundaries,
  domPointFromModelOffset,
  firstTextNodeIn,
  holdsText,
  isTextContainer,
  offsetAtElementBoundary,
  offsetWithRuns,
  resolveBoundaries,
  runsIn,
  runsOf,
  selectionDirection,
  textContainerInside,
  type DOMPoint,
  type ModelPoint,
  type ResolvedBoundaries,
  type PositionContext
} from './text-position';
