/**
 * @barocss/vnode - VNode Types
 * 
 * VNode-specific types only. DSL types are imported from @barocss/dsl.
 */

/**
 * VNode Tag Constants
 * 
 * Define special tag values as constants for type safety and typo prevention
 */
export const VNodeTag = {
  /** Special tag representing text node */
  TEXT: '#text',
  /** Tag representing portal node */
  PORTAL: 'portal',
} as const;

export type VNodeTagType = typeof VNodeTag[keyof typeof VNodeTag];

/**
 * DOM Attribute Constants
 * 
 * Define attribute names stored in DOM as constants
 */
export const DOMAttribute = {
  /** Component Schema ID (data-bc-sid) */
  BC_SID: 'data-bc-sid',
  /** Decorator Schema ID (data-decorator-sid) */
  DECORATOR_SID: 'data-decorator-sid',
  /** Decorator Schema Type (data-decorator-stype) */
  DECORATOR_STYPE: 'data-decorator-stype',
  /** Decorator Category (data-decorator-category) */
  DECORATOR_CATEGORY: 'data-decorator-category',
  /** Decorator Position (data-decorator-position) */
  DECORATOR_POSITION: 'data-decorator-position',
  /** Skip Reconcile Flag (data-skip-reconcile) */
  SKIP_RECONCILE: 'data-skip-reconcile',
  /** Decorator Flag (data-decorator) */
  DECORATOR: 'data-decorator',
} as const;

// Type for className values used in VNode attributes
export type ClassNameType = string | string[] | Record<string, boolean> | Array<string | Record<string, boolean> | Array<string | Record<string, boolean>>>;

// VNode interface - the core type for virtual DOM nodes
export interface VNode {
  tag?: string;
  text?: string | number;
  attrs?: Record<string, any>;
  style?: Record<string, any>;  // Inline styles
  children?: (string | number | VNode)[];
  // Key for efficient child matching during reconciliation
  // This is a VNode-only property and is never stored in the DOM
  key?: string;
  // Component identity information (only for component-generated VNodes)
  // These are set at the top level to indicate where the node originated from
  // They are NOT added to attrs as data-bc-* attributes (those are added by Reconciler)
  sid?: string;    // Schema ID - only set for component-generated VNodes with tag
  stype?: string;  // Schema Type - only set for component-generated VNodes with tag
  props?: Record<string, any>;      // Pure props (excluding stype/sid/type) - only for component-generated VNodes
  // Decorator VNode identity information (only for decorator-generated VNodes)
  // These are set at the top level to indicate where the decorator node originated from
  // They are NOT added to attrs as data-decorator-* attributes (those are added by Reconciler)
  decoratorSid?: string;      // Decorator Schema ID - only for decorator-generated VNodes
  decoratorStype?: string;    // Decorator Schema Type - only for decorator-generated VNodes
  decoratorCategory?: 'layer' | 'inline' | 'block';  // Decorator category - only for decorator-generated VNodes
  decoratorPosition?: 'before' | 'after' | 'inside-start' | 'inside-end' | 'overlay' | 'absolute';  // Decorator position - only for decorator-generated VNodes
  decoratorModel?: any;        // Original Decorator - only for decorator-generated VNodes (optional, for full context)
  isExternal?: boolean; // true: external component, false: contextual component - only for component-generated VNodes
  portal?: {
    target: HTMLElement;
    template: any;
    portalId?: string;
  };
  // Metadata for reconciler (e.g., selection anchoring)
  meta?: {
    isSelectionRun?: boolean;
    selectionAnchorOffset?: number;
    selectionAbsStart?: number;
    sidAutogenerated?: boolean;
    [key: string]: any;
  };
}